from pathlib import Path
p=Path('/mnt/data/v72work/src/components/TacticalBoard.tsx')
s=p.read_text()
s=s.replace("interface TacticalBoardProps {\n  formation: string;\n  opponentFormation: string;\n  lang: 'ar' | 'en' | 'es' | 'fr';\n  value?: TacticalBoardState | null;\n  onChange?: (state: TacticalBoardState) => void;\n  readOnly?: boolean;\n}","interface TacticalBoardProps {\n  formation: string;\n  opponentFormation: string;\n  lang: 'ar' | 'en' | 'es' | 'fr';\n  value?: TacticalBoardState | null;\n  onChange?: (state: TacticalBoardState) => void;\n  readOnly?: boolean;\n  showOpponent?: boolean;\n  compact?: boolean;\n}")
s=s.replace("function makeInitial(formation: string, opponentFormation: string): TacticalBoardState {\n  const own = coordinates(formation, false).map((p, i) => ({ ...p, id: `home-${i}`, name: '', isOpponent: false }));\n  const opp = coordinates(opponentFormation || '4-4-2', true).map((p, i) => ({ ...p, id: `opp-${i}`, name: '', isOpponent: true }));\n  return { players: [...own, ...opp], teamColor: '#8b5cf6', opponentColor: '#ef4444' };\n}\n\nexport default function TacticalBoard({ formation, opponentFormation, lang, value, onChange, readOnly = false }: TacticalBoardProps) {", "function makeInitial(formation: string, opponentFormation: string, showOpponent = true): TacticalBoardState {\n  const own = coordinates(formation, false).map((p, i) => ({ ...p, id: `home-${i}`, name: '', isOpponent: false }));\n  const opp = showOpponent ? coordinates(opponentFormation || '4-4-2', true).map((p, i) => ({ ...p, id: `opp-${i}`, name: '', isOpponent: true })) : [];\n  return { players: [...own, ...opp], teamColor: '#8b5cf6', opponentColor: '#ef4444' };\n}\n\nexport default function TacticalBoard({ formation, opponentFormation, lang, value, onChange, readOnly = false, showOpponent = true, compact = false }: TacticalBoardProps) {")
s=s.replace("const [board, setBoard] = useState<TacticalBoardState>(() => value?.players?.length ? value : makeInitial(formation, opponentFormation));", "const [board, setBoard] = useState<TacticalBoardState>(() => value?.players?.length ? value : makeInitial(formation, opponentFormation, showOpponent));")
s=s.replace("const formationKeyRef = useRef(`${formation}|${opponentFormation}`);", "const formationKeyRef = useRef(`${formation}|${opponentFormation}|${showOpponent}`);")
s=s.replace("const next = makeInitial(formation, opponentFormation);\n    clearLines();", "const next = makeInitial(formation, opponentFormation, showOpponent);\n    clearLines();")
s=s.replace("const key = `${formation}|${opponentFormation}`;", "const key = `${formation}|${opponentFormation}|${showOpponent}`;")
s=s.replace("const next = makeInitial(formation, opponentFormation);\n      next.teamColor", "const next = makeInitial(formation, opponentFormation, showOpponent);\n      next.teamColor")
s=s.replace("setBoard(makeInitial(formation, opponentFormation));", "setBoard(makeInitial(formation, opponentFormation, showOpponent));")
s=s.replace("}, [formation, opponentFormation, value]);", "}, [formation, opponentFormation, showOpponent, value]);")
s=s.replace("className={`pitch-container w-full ${readOnly ? 'h-[300px]' : 'h-[430px]'} rounded-2xl relative overflow-hidden shadow-2xl select-none`}", "className={`pitch-container w-full ${compact ? 'h-[260px]' : readOnly ? 'h-[300px]' : 'h-[390px]'} rounded-2xl relative overflow-hidden shadow-2xl select-none`}")
s=s.replace("w-11 h-11 rounded-full", "w-9 h-9 rounded-full")
s=s.replace("max-w-[42px]", "max-w-[34px]").replace("max-w-[40px]", "max-w-[32px]")
p.write_text(s)

p=Path('/mnt/data/v72work/src/utils/tacticalEngine.ts')
s=p.read_text()
old="""function counterFormation(style: string, profile: GameProfile): string {\n  if (style.includes('ضغط عالي')) return profile.formation.includes('4-2') ? profile.formation : '4-2-3-1';\n  if (style.includes('سرعة من الأطراف') || style.includes('عرضيات')) return '4-4-2';\n  if (style.includes('استحواذ')) return '4-3-2-1';\n  if (style.includes('دفاع متأخر')) return profile.formation.includes('3-') ? profile.formation : '4-3-3';\n  if (style.includes('لعب من العمق')) return '4-2-3-1';\n  return profile.formation;\n}\n"""
new="""function counterFormation(style: string, profile: GameProfile, oppFormation = '', matchState = ''): string {\n  const s = `${style} ${oppFormation} ${matchState}`.toLowerCase();\n  const f = (oppFormation || '').replace(/\s+/g, '');\n  if (/4-2-3-1|4231/.test(f)) return /wing|wide|أطراف|عرضيات/.test(s) ? '4-4-2' : '4-3-2-1';\n  if (/4-3-3|433|4-2-1-3|4213/.test(f)) return /possession|استحواذ/.test(s) ? '4-2-3-1' : '4-4-2';\n  if (/4-4-2|442/.test(f)) return '4-2-3-1';\n  if (/3-5-2|352|3-4-3|343/.test(f)) return '4-2-1-3';\n  if (/5-3-2|532|5-4-1|541/.test(f)) return '3-2-4-1';\n  if (/ضغط عالي|high press|press/.test(s)) return '4-2-3-1';\n  if (/سرعة من الأطراف|عرضيات|wide|wing|cross/.test(s)) return '4-4-2';\n  if (/استحواذ|possession/.test(s)) return '4-3-2-1';\n  if (/دفاع متأخر|low block|park/.test(s)) return '3-2-4-1';\n  if (/لعب من العمق|central|middle/.test(s)) return '4-2-3-1';\n  return profile.formation;\n}\n"""
s=s.replace(old,new)
s=s.replace("const formation = counterFormation(input.opponentStyle, profile);", "const formation = counterFormation(input.opponentStyle, profile, input.oppFormation, input.matchState);")
# Remove outdated efootball yearly profiles from consideration by mapping later if needed not harmful
# Make result more decisive: normalize numeric strings
s=s.replace("'4 / 10'", "'4'").replace("'5 / 10'", "'5'").replace("'6 / 10'", "'6'").replace("'7 / 10'", "'7'").replace("'8 / 10'", "'8'").replace("'9 / 10'", "'9'")
p.write_text(s)
